### ISSUE TITLE
[request]Script to add deny permission

### ISSUE THREAD

**Issue by Pafzedog** [m-dwyer/CryptoBlocker#3]
Hello,

I am very interested in your project but I just wanted to extract the script to add "deny permission" for user but I can't find it.
In fact I am already running FSRM and I have files screening already configured, it's why I just need the blocking script.
Can you share it ? 

Thanks

**Comment by m-dwyer** [comment]
Are you wanting to reuse the code to add a deny permission for a given user and share?  You should just be able to call the function DenySharePermission to achieve this.

**Comment by Pafzedog** [comment]
Yes I am.
But I don't know well PowerShell, how do you specify user and share to add  "DenySharePermission" ? 
are there variables I can use ? sorry for dumb question .... this is why I wanted to "see" your script before I made my own.

**Comment by m-dwyer** [comment]
I think this is the function you're after: https://github.com/m-dwyer/CryptoBlocker/blob/c5c1aa1bcee97dc010c79d38b2df19da4fb6f070/DeployCryptoBlocker.ps1#L100-L133

You just need to pass in the share name, and domain username.

**Comment by Pafzedog** [comment]
Thanks :)
